# Change these first
owner: tfriz343 # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: GitLab
    url: $GITLAB_SITE
  - name: Gallery
    url: $GALLERY_SITE
  - name: The Library
    url: $FOTT_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
